# Generated by Django 5.2.11 on 2026-03-30 12:39

from django.db import migrations, models

import apps.accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_add_timezone_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_crop_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_original",
            field=models.ImageField(blank=True, upload_to=apps.accounts.models.avatar_original_path),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_thumbnail",
            field=models.ImageField(blank=True, upload_to=apps.accounts.models.avatar_thumbnail_path),
        ),
    ]
