# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2
# Last updated: 2026-01-25

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - pip install uv
      - uv export --group dev --no-hashes > requirements-rtd.txt
    post_install:
      - pip install -r requirements-rtd.txt

mkdocs:
  configuration: config/mkdocs.yml
