# Generated by Django 5.2.14 on 2026-05-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="failure_count",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Number of times the handler raised. Stops retrying past WEBHOOK_MAX_FAILURES."
            ),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="last_error",
            field=models.TextField(blank=True, help_text="Truncated exception message from the most recent failure."),
        ),
    ]
