#!/usr/bin/env sh

export PY_CMD='docker-compose run --rm --no-deps web'
export JS_CMD='docker-compose run --rm --no-deps node'
export PY_FILES=$(git diff --staged --name-only HEAD | grep '.py$')
export JS_FILES=$(git diff --staged --name-only HEAD | egrep 'src/js/*')
export GREEN='\033[0;32m'
export NC='\033[0m'
export ERRORS=0

# Auto normalize/format python
echo "\n${GREEN}Formatting Python files with Black ...${NC}"
${PY_CMD} black ${PY_FILES} && git add ${PY_FILES}

if [[ -n "${PY_FILES}" ]]; then
    echo "\n${GREEN}Linting Python files ...${NC}"
    ${PY_CMD} flake8 ${PY_FILES}
    if [[ $? -ne 0 ]]; then
        export ERRORS=1
    else
        echo "${GREEN}✓ Python files okay${NC}"
    fi

    echo ""
    echo "${GREEN}Linting Python imports ...${NC}"
    ${PY_CMD} isort --recursive --check-only --diff ${PY_FILES}
    if [[ $? -ne 0 ]]; then
        export ERRORS=1
    else
        echo "${GREEN}✓ Python imports okay${NC}"
    fi
fi

if [[ -n "${JS_FILES}" ]]; then
    echo "\n${GREEN}Linting Javascript files ...${NC}"
    ${JS_CMD} npx jshint ${JS_FILES}
    if [[ $? -ne 0 ]]; then
        export ERRORS=1
    else
        echo "${GREEN}✓ Javascript files okay${NC}"
    fi
fi

if [[ ${ERRORS} -ne 0 ]]; then
    exit 1
fi
