#!/usr/bin/env sh

export PY_CMD='docker-compose run --rm --no-deps web'
export NODE_CMD='docker-compose run --rm --no-deps -e NODE_ENV=production node'
export PY_FILES=$(git diff --staged --name-only HEAD | grep '.py$')
export JS_FILES=$(git diff --staged --name-only HEAD | egrep 'src/js/*')
export SCSS_FILES=$(git diff --staged --name-only HEAD | egrep 'src/scss/*')
export GREEN='\033[0;32m'
export NC='\033[0m'
export ERRORS=0

if [[ -n "${PY_FILES}" ]]; then

    # Auto normalize/format python
    echo "\n${GREEN}Formatting Python files with Black ...${NC}"
    ${PY_CMD} black ${PY_FILES} && git add ${PY_FILES}

    echo "\n${GREEN}Linting Python files ...${NC}"
    ${PY_CMD} flake8 ${PY_FILES}
    if [[ $? -ne 0 ]]; then
        export ERRORS=1
    else
        echo "${GREEN}✓ Python files okay${NC}"
    fi

    echo ""
    echo "${GREEN}Linting Python imports ...${NC}"
    ${PY_CMD} isort --recursive --check-only --diff ${PY_FILES}
    if [[ $? -ne 0 ]]; then
        export ERRORS=1
    else
        echo "${GREEN}✓ Python imports okay${NC}"
    fi

    echo ""
    echo "${GREEN}Linting Python types ...${NC}"
    ${PY_CMD} mypy ${PY_FILES}
    if [[ $? -ne 0 ]]; then
        export ERRORS=1
    else
        echo "${GREEN}✓ Python types okay${NC}"
    fi

fi

if [[ -n "${JS_FILES}" ]]; then

    # Auto normalize/format javascript
    echo "\n${GREEN}Formatting Javascript files with Prettier ...${NC}"
    ${NODE_CMD} npx prettier --write ${JS_FILES} && git add ${JS_FILES}

    echo "\n${GREEN}Linting Javascript files ...${NC}"
    ${NODE_CMD} npx eslint ${JS_FILES}
    if [[ $? -ne 0 ]]; then
        export ERRORS=1
    else
        echo "${GREEN}✓ Javascript files okay${NC}"
    fi
fi

if [[ -n "${SCSS_FILES}" ]]; then

    echo "\n${GREEN}Formatting SCSS files with Prettier ...${NC}"
    ${NODE_CMD} npx prettier --write ${SCSS_FILES} && git add ${SCSS_FILES}

    echo "\n${GREEN}Linting SCSS files ...${NC}"
    ${NODE_CMD} npx stylelint ${SCSS_FILES}
    if [[ $? -ne 0 ]]; then
        export ERRORS=1
    else
        echo "${GREEN}✓ SCSS files okay${NC}"
    fi

fi

if [[ ${ERRORS} -ne 0 ]]; then
    exit 1
fi
