#!/usr/bin/env bash

DOWNLOAD_LOCATION='https://github.com/epicserve/django-base-site/archive/main.zip'
PROJECT_NAME_SLUG_DEFAULT='example'
PROJECT_NAME_SLUG='example'
PROJECT_DIRECTORY_DEFAULT="$(pwd)/$PROJECT_NAME_SLUG_DEFAULT"
PROJECT_DIRECTORY=''
GREEN=$(tput -Txterm setaf 2)
YELLOW=$(tput -Txterm setaf 3)
WHITE=$(tput -Txterm setaf 7)
RESET=$(tput -Txterm sgr0)

function ask_yes_or_no_default_no() {
    read -r -p "${GREEN}$1${RESET} ${WHITE}(y/N)${RESET}${GREEN}?${RESET} " response
    readonly response=`echo "$response" | tr '[:upper:]' '[:lower:]'` # to lowercase
    if [[ $response =~ ^(no|n| ) ]] || [[ -z $response ]]; then
        echo "no"
    else
        echo "yes"
    fi
}

function ask_yes_or_no_default_yes() {
    read -r -p "${GREEN}$1${RESET} ${WHITE}(Y/n)${RESET}${GREEN}?${RESET} " response
    readonly response=`echo "$response" | tr '[:upper:]' '[:lower:]'` # to lowercase
    if [[ $response =~ ^(yes|y| ) ]] || [[ -z $response ]]; then
        echo "yes"
    else
        echo "no"
    fi
}

get_project_name_slug() {
  echo -n "${GREEN}What is the project name slug${RESET} ${WHITE}[$PROJECT_NAME_SLUG_DEFAULT]${RESET}${GREEN}?${RESET} "
  read PROJECT_NAME_SLUG
  if [ -z "$PROJECT_NAME_SLUG" ]; then
    PROJECT_NAME_SLUG=$PROJECT_NAME_SLUG_DEFAULT
  fi
}

get_project_directory() {
  PROJECT_DIRECTORY_DEFAULT="$(pwd)/$PROJECT_NAME_SLUG"
  echo -n "${GREEN}What directory do you want your project in${RESET} ${WHITE}[$PROJECT_DIRECTORY_DEFAULT]${RESET}${GREEN}?${RESET} "
  read PROJECT_DIRECTORY
  if [ -z "$PROJECT_DIRECTORY" ]; then
    PROJECT_DIRECTORY=$PROJECT_DIRECTORY_DEFAULT
  fi
}

echo ""
get_project_name_slug
get_project_directory

if [ -n "$(ls -A $PROJECT_DIRECTORY 2> /dev/null)" ]; then
    if [[ "yes" = $(ask_yes_or_no_default_yes "The directory ${PROJECT_DIRECTORY} is not empty. If you continue, the contents will be removed. Do you want to continue") ]]; then
        rm -rf $PROJECT_DIRECTORY
    else
        echo "Quit. Nothing changed."
        exit
    fi
fi

curl -LOks $DOWNLOAD_LOCATION && unzip -q main
mv django-base-site-main $PROJECT_DIRECTORY
rm -rf django-base-site-main
rm main.zip
cd $PROJECT_DIRECTORY

SECRET_KEY=$(python -c "import random; print(''.join(random.SystemRandom().choice('abcdefghijklmnopqrstuvwxyz0123456789%^&*(-_=+)') for i in range(50)))")
cat > .env <<EOF
DEBUG=on
SECRET_KEY='$SECRET_KEY'
EOF

make remove_extra_files
USING_COMPOSE="yes"

if [[ "no" = $(ask_yes_or_no_default_yes "Are going to use Docker Compose") ]]; then
    make remove_docker_compose
    USING_COMPOSE="no"
else
    echo "DATABASE_URL=postgres://postgres@db:5432/postgres" >> .env
fi

if [[ ${USING_COMPOSE} = "no"  ]]; then

    python -m venv .venv && source .venv/bin/activate
    pip install --upgrade pip
    pip install --upgrade pip-tools
    pip install --upgrade --requirement ./config/requirements/dev.in
    python $PROJECT_DIRECTORY/manage.py migrate
    python $PROJECT_DIRECTORY/manage.py createsuperuser
    echo ""
    echo "Done."
    echo ""
    echo "To start the Django runserver in your new project:"
    echo "$ cd $PROJECT_DIRECTORY"
    echo "$ npm i"
    echo "$ source .venv/bin/activate"
    echo "$ ./manage.py runserver"

elif [[ ${USING_COMPOSE} = "yes" ]]; then

    echo ""
    echo "Done."
    echo ""
    echo "To start Docker Compose run:"
    echo "$ cd $PROJECT_DIRECTORY"
    echo "$ docker-compose up"
    echo ""

fi
