# Generated by Django 5.2.3 on 2026-04-26 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='description',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='name',
        ),
    ]
