# Generated by Django 5.2.3 on 2026-04-26 03:08

from django.db import migrations


def remove_recurring_instance_lines(apps, schema_editor):
    TransactionLine = apps.get_model('budget', 'TransactionLine')
    TransactionLine.objects.filter(transaction__recurring__isnull=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_budget_name_description'),
    ]

    operations = [
        migrations.RunPython(remove_recurring_instance_lines, migrations.RunPython.noop),
    ]
