# Generated by Django 5.2.3 on 2026-04-26 03:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_remove_recurring_instance_lines'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month this assignment applies to.')),
                ('assigned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_budgets', to='budget.budget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_budgets', to='budget.category')),
            ],
            options={
                'ordering': ['month', 'category__name'],
                'unique_together': {('budget', 'category', 'month')},
            },
        ),
    ]
