# Generated by Django 3.1.7 on 2021-03-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="billing_email",
            field=models.EmailField(
                blank=True, help_text="The email address that receipts are sent.", max_length=254, null=True
            ),
        ),
    ]
