# Generated by Django 5.2.11 on 2026-03-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_alter_organization_id_alter_organizationinvite_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="primary"),
        ),
    ]
