name: Upgrade Python Packages

on:
  schedule:
    - cron: '0 10 * * 6'  # Run every Sunday at 5:00 AM CDT
  workflow_dispatch:

jobs:
  create_pr:
    name: Create Pull Request
    runs-on: ubuntu-latest

    outputs:
      upgrades: ${{ steps.diff.outputs.upgrades }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run uv sync to upgrade packages
      run: |
        pip install --upgrade pip uv
        # Create a backup of the current lock file
        if [ -f uv.lock ]; then
          cp uv.lock uv.lock.bak
        fi
        # Sync and upgrade all dependencies
        uv sync --upgrade
        # Create lock file if it doesn't exist
        if [ ! -f uv.lock ]; then
          uv lock
        else
          # Update the lock file with new resolved dependencies
          uv lock --upgrade
        fi

    - name: Generate diff and extract package upgrades
      id: diff
      run: |
        if [ -f uv.lock.bak ]; then
          # Generate diff, pipe to the script, and capture the output
          upgrades_output=$(git diff uv.lock | scripts/parse_uv_diff.py)
          # Set the GitHub output variable using heredoc to preserve multiline
          echo "upgrades<<EOF" >> "$GITHUB_OUTPUT"
          echo "$upgrades_output" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
        else
          echo "No previous lock file found. Cannot generate diff."
          echo "upgrades=No previous lock file found. This is the initial lock file creation." >> "$GITHUB_OUTPUT"
        fi
        # Remove backup file
        rm -f uv.lock.bak
    
    - name: Show package upgrades
      run: |
          echo "${{ steps.diff.outputs.upgrades }}"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        title: "Upgrade Python packages"
        commit-message: |
          Upgrade Python packages

          ${{ steps.diff.outputs.upgrades }}
        body: |
          ${{ steps.diff.outputs.upgrades }}
        branch: "task/upgrade-python-packages"
