# Generated by Django 5.2.13 on 2026-05-06 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("organizations", "0004_add_is_primary_to_organizationmember"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("mention", "Mention"), ("email", "Email")],
                        help_text="Category of event. Drives icon/grouping in the UI.",
                        max_length=32,
                    ),
                ),
                ("target_object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                ("url", models.CharField(max_length=500)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("read_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user whose action produced this notification (null for system events).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Org scope; null for personal/global notifications.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="organizations.organization",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="The user who will see this notification in their inbox.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "indexes": [
                    models.Index(
                        fields=["recipient", "organization", "-created"], name="notificatio_recipie_6e705f_idx"
                    ),
                    models.Index(
                        fields=["recipient", "organization", "read_at"], name="notificatio_recipie_40360d_idx"
                    ),
                    models.Index(
                        fields=["target_content_type", "target_object_id"], name="notificatio_target__dfbaf5_idx"
                    ),
                ],
            },
        ),
    ]
