# Generated by Django 5.2.13 on 2026-05-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("in_app", "In-app notification"), ("email", "Email")],
                help_text="Category of event. Drives icon/grouping in the UI.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
